### ISSUE TITLE
Tooling used to create list?

### ISSUE THREAD

**Issue by EvanCarroll** [stefangabos/world_countries#15]
It would be nice if you could open up the tooling used to create this list.

**Comment by gexclaude** [comment]
I need the countries as java properties files - if I had access to the tooling / templates I could contribute

**Comment by stefangabos** [comment]
that part is a mess so I am currently not willing to share it - not excluded that I will share it at some point when I'll have the time to make it readable for humans. 

if you show me what you need I'd be glad to add that specific format
