### ISSUE TITLE
Where is Taiwan?

### ISSUE THREAD

**Issue by fenric** [stefangabos/world_countries#20]

**Comment by stefangabos** [comment]
Taiwan is [officially](https://en.wikipedia.org/wiki/Taiwan) the Republic of China

**Comment by fenric** [comment]
> Taiwan is [officially](https://en.wikipedia.org/wiki/Taiwan) the Republic of China

Thank you very much! I did not know... But business is out of politics... Ok, let's add it manually :)

**Comment by stefangabos** [comment]
I was too quick answering that...
You have Taiwan in the "world.*" files. And that's because of its [sovereignty](https://en.wikipedia.org/wiki/List_of_sovereign_states) not being recognised by all the other countries.

**Comment by peter279k** [comment]
Actually it should have the `tw` directory in `data` folder.

We use the traditional Chinese word, and the simplified Chinese is in China.

According to the [country code reference site](https://countrycode.org/), we can find that the Taiwan country code is `TW`.

If possible, I can create the related PR about this :).
