### ISSUE TITLE
 The country Jersey is not in the database.

### ISSUE THREAD

**Issue by nguaman** [stefangabos/world_countries#23]
https://en.wikipedia.org/wiki/Jersey

{ 
    "id" : NumberInt(895), 
    "name" : "Jersey", 
    "alpha2" : "je", 
    "alpha3" : "jey"
}

**Comment by stefangabos** [comment]
Apparently Jersey is not considered as a country but a self-governing Crown dependency of the United Kingdom
https://en.wikipedia.org/wiki/List_of_sovereign_states#United_Kingdom

You can find Jersey in the "world" file where all the countries, territories, and areas of geographical interest that have an officially assigned ISO 3166-1 code can be found, not just those that are officially called "countries"
