### ISSUE TITLE
wrong format of swiss flag

### ISSUE THREAD

**Issue by maisen20** [stefangabos/world_countries#26]
The swiss flag has the wrong format.
It should have a square format and not a rectangle.

https://www.swissinfo.ch/eng/olympic-parade_the-swiss-flag-is-square---except-when-it-isn-t/43873350

**Comment by stefangabos** [comment]
i don't know what is the appropriate action to this...
i'll just leave it as it is i guess. it will not look ok when being present alongside other flags...
suggestions are welcome though

**Comment by StringEpsilon** [comment]
Swiss law defines square. Only exceptions according to the flag code are maritime flags.

I think the appropriate thing to do is to use the flag as the country itself specified it.

Related: The Nepalese flag also stands out, but has the correct shape in this repository:

https://github.com/stefangabos/world_countries/blob/master/flags/128x128/np.png

**Comment by stefangabos** [comment]
i am not managing the flags myself. the flags are made by [IconDrawer](http://icondrawer.com/flag-icons.php). you can either try and get in touch with them or, if you are able, alter the flags yourself and do a pull request.
again, suggestions are welcome

**Comment by stefangabos** [comment]
nevermind, I am writing an email to them right now

**Comment by stefangabos** [comment]
done - email sent

**Comment by stefangabos** [comment]
i got no response from the creators of the maps, closing this as there's nothing else i can do
