### ISSUE TITLE
Downloaded JSON from webpage is not readable

### ISSUE THREAD

**Issue by theevann** [stefangabos/world_countries#27]
I used [the webpage](http://stefangabos.github.io/world_countries/) to download a custom build with JSON formatted data.
While csv and sql are perfectly readable, I can't read the JSON file :

![image](https://user-images.githubusercontent.com/3309183/70397474-d1cfa000-1a12-11ea-9c36-844c054b57fa.png)

I used latest firefox and windows 10.

**Comment by stefangabos** [comment]
Should be fixed now

**Comment by theevann** [comment]
Perfect 👍
