### ISSUE TITLE
Combined list with 1 column for each translation (alternative: Add english name to the translated files)

### ISSUE THREAD

**Issue by JensGJ** [stefangabos/world_countries#29]
I am looking for a country list that has the name of the country in different languages (e.g. instead of 23 datasets each containing 1 name column, I'd prefer 1 set having 23 name columns (using some standard naming structure - e.g. name<XX> where <XX> is the iso_alpha2 code for the particular translation). 

A different approach could be to simply add the English name as a distinct column in the 22 translated versions of the file. In many use cases there is a need for a local language + English as the international "fall back".

**Comment by stefangabos** [comment]
I am working on this and will hopefully be available in a week

**Comment by xavhoff** [comment]
@stefangabos Is there anything new about this ?
