### ISSUE TITLE
Custom download - flags images corrupted

### ISSUE THREAD

**Issue by DarkRoku12** [stefangabos/world_countries#30]
On the web page, if i download the master (first download button), there is no issue.

But if i request a partial download, just selecting what i need, like, for example 64x64 flags only, then i hit download, i would get the .png files corrupted (can't be read).

This issue is not only for 64x64 but for any custom/partial download of flags in .png format.

**Comment by stefangabos** [comment]
Should work now. Thank you for reporting this!
