### ISSUE TITLE
English translation of Viet Nam

### ISSUE THREAD

**Issue by StefanJanssen95** [stefangabos/world_countries#37]
English isn't my first language but when I saw the name for "Viet Nam" it felt off. I double checked  and it seems to me that the name should be Vietnam".

https://en.wikipedia.org/wiki/Vietnam
https://politics.stackexchange.com/questions/25642/preferred-or-correct-english-spelling-vietnam-or-viet-nam

**Comment by stefangabos** [comment]
The lists are not compiled by hand. the English names are taken from [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1)

**Comment by stefangabos** [comment]
But, indeed, the link points to the page where it is spelled as *Vietnam*

**Comment by stefangabos** [comment]
I've updated the Wikipedia page and next time - unless somebody changes it back - it should become available with the new name. Thanks!

**Comment by stefangabos** [comment]
My change on Wikipedia was reverted and the ISO page was given as argument, to which I have to agree
https://www.iso.org/obp/ui/#iso:code:3166:VN
