### ISSUE TITLE
JSON with data URI flags

### ISSUE THREAD

**Issue by rolandtoth** [stefangabos/world_countries#41]
Many thanks for this stuff, it came really handy to me.

It would be nice if you could provide a JSON file that would contain flags as data URI strings, or perhaps just an additional JSON with alpha2 + data URI properties. This way they could be downloaded in one request instead of many. For example, in a current project we needed a country dropdown with flags and that would mean 193 individual image request. 

![image](https://user-images.githubusercontent.com/5349356/95384700-47372600-08ed-11eb-9ece-b3506f19cdb5.png)

I manually created such JSON in a web controller and added to a cache, but an "official" version would be nice.

**Comment by stefangabos** [comment]
can you please send me that JSON you created, so I can use it as a starting point? thanks!

**Comment by rolandtoth** [comment]
Hi,

actually I just finished writing a crawler that gets country data from these places:

https://restcountries.eu/rest/v2/all
https://www.countryflags.io/

I need multilanguage country names so I think I'll use the country codes and lookup localized values.

[countries.json.txt](https://github.com/stefangabos/world_countries/files/5345903/countries.json.txt)

**Comment by stefangabos** [comment]
awsome, thank you!

**Comment by rolandtoth** [comment]
Btw I could do several JSON files like this per language, but that would be too large.

**Comment by stefangabos** [comment]
This is now available since [2.3.0](https://github.com/stefangabos/world_countries/releases/tag/2.3.0)
I'd love some feedback if that's possible. 
Thanks!

**Comment by rolandtoth** [comment]
Hi,

many thanks for the update, unfortunately I'm not working on any project where I can could this. But will definitely try this out when there'll be one.
