### ISSUE TITLE
How to add flags inside to database

### ISSUE THREAD

**Issue by PeterPoll** [stefangabos/world_countries#45]
Hello! 

Sorry about my question maybe it will be out of logic but how can i added the flags inside to database you privide ? Also flags i downloaded from your code.

Thank you very much!

**Comment by stefangabos** [comment]
See [this](https://github.com/stefangabos/world_countries/issues/41) for somebody who added them as URI encoded values to the JSON
Or you could write a script to URI encode all the images then add that to the database
Or, maybe you can add the images themselves in a blob-type column (I am only familiar with MySQL so I don't know the equivalent in other database engines)

**Comment by PeterPoll** [comment]
Hello and thank you for your quick response,

I'm also using MySQL and i want to save flags of countries to make request
in my database from a project. I will add table with all countries via SQL
code you have inside your zip file but how match them with each flag ?
But my question is, it is a correct way to save photos as blod-type ?

Thank you very much and sorry if my questions are really basic.

**Comment by stefangabos** [comment]
The matching is done via the `alpha-2` code - the flags are named using that.
search [stackoverflow](https://stackoverflow.com/questions/14704559/how-to-insert-image-in-mysql-databasetable) on how to add images to database

**Comment by PeterPoll** [comment]
Ok thank you very much!

And the different of word and countries data?

Thank you very much!

**Comment by stefangabos** [comment]
It's [right there](https://github.com/stefangabos/world_countries#world-countries-)

**Comment by PeterPoll** [comment]
Hello,

sorry about many questions.

I'm trying to add all flags images to each image but i don't know the
exactly mysql query. Do you have something for me please?

there is 249 countries so it will be so bad if enter each one manually.


Thank you very much!
