### ISSUE TITLE
alpha-2 and alpha-3 data violates ISO 3166-1:2020

### ISSUE THREAD

**Issue by michael-o** [stefangabos/world_countries#50]
Chapter 5.1 says:
> LATIN CAPITAL LETTER A through LATIN CAPITAL LETTER Z; Code elements alpha-2 and alpha-3 are formed with LETTERS, 

All country codes in data is wrong because it does not use uppercase letters, but lowercase letters. Lowercase letters are used with ISO 639 for languages only.

Please correct the data.

**Comment by stefangabos** [comment]
wow, thanks for the update!
however, i will not fix this as the library is already widely used and i would break the internet :)

**Comment by michael-o** [comment]
The lease this open and add an import note to the README.

**Comment by stefangabos** [comment]
Sure, that I can do - can you please provide me the link to the docs where you found this information?

**Comment by michael-o** [comment]
Well, access to ISO documents isn't unfortunately free: https://www.iso.org/obp/ui/#iso:std:iso:3166:-1:ed-4:v1:en. You have to buy the full document. I have full access to most standards document on the planet thanks to my employer, but [here](https://www.iso.org/obp/ui/#search) is a free-of-charge official list from the ISO. Select country codes and hit search.
