### ISSUE TITLE
php - use return statement instead of assignment

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [stefangabos/world_countries#58]
Hopefully code samples explain all ;)

## Current
```php
require '...../world.php'; // $world = [...]

// where the heck the $world variable is coming from? phpstan/psalm/editor complains about undefined variable
print_r($world); 
```

## Proposal
```php
$world = require '...../world.php'; // return [...]

// all is well
print_r($world); 
```

**Comment by stefangabos** [comment]
This is now done
`$world = require '...../world.php';` now works as you'd expect.
Thanks for suggesting this!

**Comment by jacekkarczmarczyk** [comment]
it seems that this change is not included in 2.4.0 release although the README is already updated to the new format?

**Comment by stefangabos** [comment]
i haven't done a release yet containing the change - you'll have to download latest by clicking on the green "Code" button and then choosing "Download as ZIP". 
I am making some updates these days and I'll probably make a release next week

**Comment by stefangabos** [comment]
I forgot to add your name to the changelog - i just fixed that. thanks again!
