### ISSUE TITLE
Looks like St Helen is missing

### ISSUE THREAD

**Issue by Dom911** [stefangabos/world_countries#59]
Hi,

the country(?) St Helen is missing:
Saint Helena (and/or) Ascension Island (and/or) Tristan da Cunha

ISO 3166-1
Alpha-2 code: SH
Alpha-3 code: SHN
Numeric code: 654

**Comment by stefangabos** [comment]
It's not, it is in the world.* files

**Comment by Dom911** [comment]
Yes, I have seen that it was some times present but not always like bg and many others.
