### ISSUE TITLE
What about CountryCode xk Kosovo it is missing

### ISSUE THREAD

**Issue by codingyourlife** [stefangabos/world_countries#62]
I use this as backend JSON and we have a new frontend package. It lead to the error that CountryCode xk does not exist. Seems that's Kosovo. I guess it should be part of the list, right?

**Comment by stefangabos** [comment]
If you read the description of the library, you'll notice that the `countries.*` files
> contain 195 entries made up from the 193 sovereign states (commonly referred to as countries) that are members of the [United Nations (UN)](http://www.un.org/en/member-states/index.html) plus the 2 [observer states](https://en.wikipedia.org/wiki/United_Nations_General_Assembly_observers) of Palestine and the Vatican City State.

and then there's a note stating that 
> Note that there are 206 [sovereign states](https://en.wikipedia.org/wiki/List_of_sovereign_states) in the world, the 11 states that are missing from the countries list being the ones having their sovereignty disputed. See the list of sovereign states with information on their status and recognition of their sovereignty.

therefore, Kosovo is in the extended list contained in the `world.*` files
