### ISSUE TITLE
Typo in readme causing error

### ISSUE THREAD

**Issue by KRens** [stefangabos/world_countries#64]
In the readme.md there are a few error's causing error's in the code.
`search_county(array('id' => 250});
search_county(array('alpha2' => 'fr'});
search_county(array('alpha3' => 'fra'});`

=> 
1) This should be search_country instead of county!
2) This should be )); instead of });
3) $countries = require 'path/to/countries.php'; does not work, you need just require 'path/to/countries.php';
This one already creates the $countries variable.
4) Your sample code does not seem to work with the _combined file.

The sample php code also does not work, I get following error:
Fatal error: Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, int given in C:\xampp\htdocs\account.php:214 Stack trace: #0 C:\xampp\htdocs\account.php(214): array_filter(1, Object(Closure)) #1 C:\xampp\htdocs\account.php(222): search_country(Array) #2 {main} thrown in C:\xampp\htdocs\account.php on line 214

I tried both loading the _combined as the language specific file, neither solves the issue.
/vendor/stefangabos/world_countries/data/countries/en/countries.php

+ Maybe add an example how to use it using composer?

**Comment by stefangabos** [comment]
Thanks for the feedback!
That code was built before the combined lists were available...I'll think of something but for now I'll leave it like that

**Comment by stefangabos** [comment]
...also the combined lists in PHP are broken, I am just noticing that now

**Comment by KRens** [comment]
Ok, point 1 to 3 are quick fixes for you, 
I got it working without the combined one for now.

Point 4: ok, clear, something for the future.

**Comment by KRens** [comment]
Your commit did not fix point number 3 ;-)

**Comment by stefangabos** [comment]
it works for me on PHP 7.3.19
what version are you using?

**Comment by stefangabos** [comment]
the PHP files that I have don't have a variable name in them and look like this 
```php
<?php return array(
    4   => array('id' => 4  , 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'Afghanistan'),
    8   => array('id' => 8  , 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'Albania'),
```

**Comment by stefangabos** [comment]
i fixed the combined lists in PHP - as in, they now work instead of being broken. the function in the readme.md still doesn't apply for the combined data

**Comment by stefangabos** [comment]
I added a note in the README.md highlighting the fact that the functions work for the non-combined data sets

**Comment by stefangabos** [comment]
thanks for your feedback!

**Comment by KRens** [comment]
$countries = require 'path/to/countries.php'; doesn't work for me.
require 'path/to/countries.php';  does

This since the php file file already contains "$countries = array(" and puts it in the correct variable.

I'm using PHP 7.4.26

**Comment by stefangabos** [comment]
the php file does **not** contain `$counties = array(` 
you must be using an older version

**Comment by stefangabos** [comment]
ah, i see now - i don't yet have a release with the updates done to the PHP files - my bad
