### ISSUE TITLE
Armenian country and subdivision names

### ISSUE THREAD

**Issue by t1gr4n** [stefangabos/world_countries#68]
Hi!
I'd like to contribute the Armenian translations for country and also (some) subdivision names. In #60 you mention you do not take any direct contributions for country names but rather fetching them from Wikipedia. If that's the case, this is the page that can be used for it https://hy.wikipedia.org/wiki/ISO_3166-1. Please suggest if the format is not suitable, or otherwise if the direct PR with translation is needed.
Also, any idea how to maintain subdivision name translations?

**Comment by stefangabos** [comment]
Would be nice to use the same format as used for the other languages. If that is too much of a trouble I will adapt my script to fetch data from the page you indicated. Still, it has to have the exact same number of codes/countries as the ones that we already have

As for the subdivisions, [here](https://github.com/stefangabos/world_countries/tree/master/data/subdivisions) is how to contribute

**Comment by t1gr4n** [comment]
Let me look into changing the page format, that would be better.

**Comment by t1gr4n** [comment]
@stefangabos , I have updated the content at https://hy.wikipedia.org/wiki/ISO_3166-1 to the table format and added the missing entries. Please let me know if any further changes are needed.
As per the subdivisions, the mentioned [link](https://github.com/stefangabos/world_countries/tree/master/data/subdivisions?rgh-link-date=2022-06-17T19%3A22%3A22Z) only describes how to contribute to the list of the subdivisions, but I'm having hard time to figure out how to provide translations. The current format for subdivisions does not seem to support multiple languages, any plans for that?
There are valid use cases for having subdivisions in multiple languages I'd be happy on help out on that, please suggest.

**Comment by stefangabos** [comment]
great job with that page! I am going to work on adding it later on today. 
as for the subdivisions page, as per description, you are supposed to add/edit entries in the `csv` file and create a pull-request. the ISO-3166-2 standard has english names only; see [here](https://en.wikipedia.org/wiki/ISO_3166-2)

**Comment by stefangabos** [comment]
...but i am open on extending the data for the subdivisions but i don't have a good resource for all the data, in all the supported languages

**Comment by stefangabos** [comment]
I found one single issue

Turkey is missing

Turkey | TR | TUR | 792 | ISO 3166-2:TR
-- | -- | -- | -- | --

**Comment by stefangabos** [comment]
...nevermind, it's there it's just that my script didn't pick it up for some reason, sorry

**Comment by stefangabos** [comment]
i've added the Armenian language and published a new version
thanks a lot for your work!

**Comment by t1gr4n** [comment]
Thanks a lot!
