### ISSUE TITLE
Language Requests (Croatian, Serbian, Slovene)

### ISSUE THREAD

**Issue by AppyxDaniel** [stefangabos/world_countries#73]
Hi,

is it possible to add the following languages? 

- Croatian (https://hr.wikipedia.org/wiki/ISO_3166-1)
- Serbian (https://sr.wikipedia.org/wiki/ISO_3166-1)
- Slovene (https://sl.wikipedia.org/wiki/ISO_3166)

If not, what would need to be done in order to add those languages? 

Thanks in advance!

**Comment by stefangabos** [comment]
For Croatian I'll have to update my script first as it currently expects tables. I'll update it so that it can also read lists like that. Afterwards I will be able to tell if something is missing or not.

The following are missing for Serbian
```
Bonaire, Sint Eustatius and Saba, bq, 535, bes
Curaçao, cw, 531, cuw
Saint Barthélemy, bl, 652, blm
Saint Martin (French part), mf, 663, maf
Sint Maarten (Dutch part), sx, 534, sxm
South Sudan, ss, 728, ssd
Sudan, sd, 729, sdn]
```
For Slovene, the following are missing

```
Bonaire, Sint Eustatius and Saba, bq, 535, bes
Curaçao, cw, 531, cuw
Guernsey, gg, 831, ggy
Isle of Man, im, 833, imn
Jersey, je, 832, jey
Montenegro, me, 499, mne
Saint Barthélemy, bl, 652, blm
Saint Martin (French part), mf, 663, maf
Serbia, rs, 688, srb
Sint Maarten (Dutch part), sx, 534, sxm
Sudan, sd, 729, sdn
```

In all cases, note that there s Sudans

```php
728 => array('id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'South Sudan'),
729 => array('id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'Sudan'),
```

**Comment by stefangabos** [comment]
I've checked and both look good!
I'll add them over the weekend and will try to make time for updating my script so that we can check Croatian.
Thanks a lot for you work!

**Comment by stefangabos** [comment]
I found one thing
In Slovenian, the numeric code for [Srbija](https://sl.wikipedia.org/wiki/Srbija) needs to be `688` instead of `891`

**Comment by AppyxDaniel** [comment]
Oh sorry, I did not double check for duplicate names. Srbija existed twice in this list: once with `891` (Serbia and Montenegro) and one with `688`. Since Serbia and Montenegro are now two separate entries, I removed the `891`

**Comment by stefangabos** [comment]
Thanks for the quick update, I added both languages and published a new release.
I'll try to find time over the weekend for adding the Croatian language.
Please drop me a comment if you don't hear from me over the weekend as I tend to forget :) I am managing a lot of open source projects, work and family :)
Thanks again!

**Comment by stefangabos** [comment]
For Croatian

The following are missing

AX Åland Islands
BQ Bonaire, Sint Eustatius and Saba
CW Curaçao
PS Palestine, State of
BL Saint Barthélemy
MF Saint Martin (French part)
SX Sint Maarten (Dutch part)
SS South Sudan

The following need to be removed

AN Nizozemski Antili
TB Tibet

**Comment by AppyxDaniel** [comment]
Please check again. I updated the source.

**Comment by stefangabos** [comment]
I added Croatian and made a new release.
Thanks a lot for you contributions!
