### ISSUE TITLE
[bug] Flag JSON files are empty

### ISSUE THREAD

**Issue by Jeromearsene** [stefangabos/world_countries#77]
In README, we can read this:
> Flag images are also available as single JSON files, one for each of the available sizes, containing all flag images as data-uri

But the package (`2.8.1`) installed with `pnpm` are all JSON flag files = `[]`

<img width="1034" alt="Capture d’écran 2023-06-29 à 15 58 48" src="https://github.com/stefangabos/world_countries/assets/9333686/93a85f1f-145c-43a4-a2a6-96ce24fcdf23">

**Comment by stefangabos** [comment]
Thanks for reporting!
