### ISSUE TITLE
German country name for UK is longer then 50 characters as defined as max column length

### ISSUE THREAD

**Issue by markovanderpuil** [stefangabos/world_countries#8]
(826, 'de', 'Vereinigtes Königreich Großbritannien und Nordirland') is 52 characters and probably longer in UTF-8 multibyte.

Propose to increase
`name` varchar(50) NOT NULL DEFAULT '',
to
`name` varchar(60) NOT NULL DEFAULT '',

in world_countries/data/de/countries.sql on line 7

There may be more languages for which this is true....

**Comment by stefangabos** [comment]
Thanks!
