### ISSUE TITLE
Countries file contains 193 instead of 195 countries

### ISSUE THREAD

**Issue by mikehaertl** [stefangabos/world_countries#83]
The README states that:

> countries.*	Files named like this contain 195 entries made up from the 193 sovereign states (commonly refered to as countries) that are members of the [United Nations (UN)](https://www.un.org/about-us/member-states) plus the 2 [observer states](https://en.wikipedia.org/wiki/United_Nations_General_Assembly_observers) of Palestine and the Vatican City State.

https://github.com/stefangabos/world_countries/blob/c82e357632281a8eb151d2331b3fe5e280f677b8/README.md?plain=1#L16

But the actual file does not contain the 2 observer states. I guess this should be fixed in the README.

**Comment by stefangabos** [comment]
Done.
Thanks!
