### ISSUE TITLE
Fail to install using npm

### ISSUE THREAD

**Issue by inigomarquinez** [stefangabos/world_countries#84]
I found this repository great and I wanted to use it in a nodejs project.

Instead of downloading the files, I would like to keep it as a dependency in my `package.json` file so I can update the dependency whenever you release a new version. But when I try to install it by running:

```
npm i stefangabos/world_countries
```

It throws the following error:

```
npm i stefangabos/world_countries
npm WARN tarball tarball data for world_countries_lists@git+ssh://git@github.com/stefangabos/world_countries.git#c82e357632281a8eb151d2331b3fe5e280f677b8 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for world_countries_lists@git+ssh://git@github.com/stefangabos/world_countries.git#c82e357632281a8eb151d2331b3fe5e280f677b8 (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
```

**Comment by stefangabos** [comment]
that's not my package...
`npm install world_countries_lists` 
will get you mine
