### ISSUE TITLE
Add Netherlands Antilles

### ISSUE THREAD

**Issue by bobylito** [stefangabos/world_countries#89]
Hello and thanks for this amazing resource that you keep up to date.

We use this database as a way to populate a list of birth countries and we encountered a delicate case : one user was born in the Netherlands Antilles, which was disbanded in 2010. The birth country information is a requirement for our business and using Netherlands for example would not be accurate. Would it be possible to integrate back such a country?

Thanks

**Comment by stefangabos** [comment]
we currently don't have support for historical data. you'll have to manually add that entry I'm afraid

**Comment by bobylito** [comment]
Sounds fair. Thanks for your answer :)
