### ISSUE TITLE
Anarctica is not a country

### ISSUE THREAD

**Issue by AyubM** [stefangabos/world_countries#9]
I think some penguin partisans have hacked your computer.

In seriousness, there is a lack of trimmed down list of countries.

The ISO should not be a trusted authority on sovereignty or nationality.

I'm taking your list and trimming out anything that isn't a part of the UN: http://www.un.org/en/member-states/

I can submit a pull request if you want to include it. There is surprisingly a missing dataset of UN member states.

**Comment by stefangabos** [comment]
You are right! Will fix it as soon as I have the time. Thanks!

**Comment by stefangabos** [comment]
Fixed, thanks
